POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "User 02",
    "password": "234"
}

###

GET http://localhost:5000/api/movies/trendingssss
Authorization: : "Bearer RYoOcWM4JW"

###
POST http://localhost:5000/api/movies/search
# Content-Type: application/json
Authorization: `Bearer RYoOcWM4JW`,

{
    "genre" : "18",
    "language" : "en",
    "mediatype" :"movie",
    "name" : "minion",
    "year" : "2022",
}